// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/iam.proto

package iamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户相关消息
type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_proto_iam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_iam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_iam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_iam_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 策略相关消息
type CreatePolicyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	PolicyDocument string                 `protobuf:"bytes,3,opt,name=policy_document,json=policyDocument,proto3" json:"policy_document,omitempty"` // JSON字符串
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePolicyRequest) Reset() {
	*x = CreatePolicyRequest{}
	mi := &file_proto_iam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePolicyRequest) ProtoMessage() {}

func (x *CreatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePolicyRequest.ProtoReflect.Descriptor instead.
func (*CreatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePolicyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePolicyRequest) GetPolicyDocument() string {
	if x != nil {
		return x.PolicyDocument
	}
	return ""
}

type AttachUserPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	PolicyName    string                 `protobuf:"bytes,2,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachUserPolicyRequest) Reset() {
	*x = AttachUserPolicyRequest{}
	mi := &file_proto_iam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachUserPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachUserPolicyRequest) ProtoMessage() {}

func (x *AttachUserPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachUserPolicyRequest.ProtoReflect.Descriptor instead.
func (*AttachUserPolicyRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_proto_rawDescGZIP(), []int{4}
}

func (x *AttachUserPolicyRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *AttachUserPolicyRequest) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

type AttachUserPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachUserPolicyResponse) Reset() {
	*x = AttachUserPolicyResponse{}
	mi := &file_proto_iam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachUserPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachUserPolicyResponse) ProtoMessage() {}

func (x *AttachUserPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachUserPolicyResponse.ProtoReflect.Descriptor instead.
func (*AttachUserPolicyResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_proto_rawDescGZIP(), []int{5}
}

func (x *AttachUserPolicyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Policy struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PolicyDocument string                 `protobuf:"bytes,4,opt,name=policy_document,json=policyDocument,proto3" json:"policy_document,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_proto_iam_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_proto_iam_proto_rawDescGZIP(), []int{6}
}

func (x *Policy) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Policy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Policy) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Policy) GetPolicyDocument() string {
	if x != nil {
		return x.PolicyDocument
	}
	return ""
}

func (x *Policy) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Policy) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 访问密钥相关消息
type CreateAccessKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccessKeyRequest) Reset() {
	*x = CreateAccessKeyRequest{}
	mi := &file_proto_iam_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccessKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccessKeyRequest) ProtoMessage() {}

func (x *CreateAccessKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccessKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateAccessKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_proto_rawDescGZIP(), []int{7}
}

func (x *CreateAccessKeyRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type ListAccessKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccessKeysRequest) Reset() {
	*x = ListAccessKeysRequest{}
	mi := &file_proto_iam_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessKeysRequest) ProtoMessage() {}

func (x *ListAccessKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessKeysRequest.ProtoReflect.Descriptor instead.
func (*ListAccessKeysRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_proto_rawDescGZIP(), []int{8}
}

func (x *ListAccessKeysRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type UpdateAccessKeyStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId   string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // active/inactive
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccessKeyStatusRequest) Reset() {
	*x = UpdateAccessKeyStatusRequest{}
	mi := &file_proto_iam_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccessKeyStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccessKeyStatusRequest) ProtoMessage() {}

func (x *UpdateAccessKeyStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccessKeyStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccessKeyStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateAccessKeyStatusRequest) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *UpdateAccessKeyStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AccessKey struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId     string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	SecretAccessKey string                 `protobuf:"bytes,2,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"` // 仅在创建时返回
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	UserName        string                 `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AccessKey) Reset() {
	*x = AccessKey{}
	mi := &file_proto_iam_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessKey) ProtoMessage() {}

func (x *AccessKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessKey.ProtoReflect.Descriptor instead.
func (*AccessKey) Descriptor() ([]byte, []int) {
	return file_proto_iam_proto_rawDescGZIP(), []int{10}
}

func (x *AccessKey) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *AccessKey) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

func (x *AccessKey) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AccessKey) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *AccessKey) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AccessKey) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListAccessKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessKeys    []*AccessKey           `protobuf:"bytes,1,rep,name=access_keys,json=accessKeys,proto3" json:"access_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccessKeysResponse) Reset() {
	*x = ListAccessKeysResponse{}
	mi := &file_proto_iam_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessKeysResponse) ProtoMessage() {}

func (x *ListAccessKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessKeysResponse.ProtoReflect.Descriptor instead.
func (*ListAccessKeysResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_proto_rawDescGZIP(), []int{11}
}

func (x *ListAccessKeysResponse) GetAccessKeys() []*AccessKey {
	if x != nil {
		return x.AccessKeys
	}
	return nil
}

// 验证相关消息
type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId   string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	RequestData   string                 `protobuf:"bytes,3,opt,name=request_data,json=requestData,proto3" json:"request_data,omitempty"` // 序列化的请求数据
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                        // ISO8601格式
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_proto_iam_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_proto_rawDescGZIP(), []int{12}
}

func (x *VerifyRequest) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *VerifyRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *VerifyRequest) GetRequestData() string {
	if x != nil {
		return x.RequestData
	}
	return ""
}

func (x *VerifyRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_proto_iam_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_proto_rawDescGZIP(), []int{13}
}

func (x *VerifyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type CheckPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Resource      string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionRequest) Reset() {
	*x = CheckPermissionRequest{}
	mi := &file_proto_iam_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionRequest) ProtoMessage() {}

func (x *CheckPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_proto_rawDescGZIP(), []int{14}
}

func (x *CheckPermissionRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CheckPermissionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckPermissionRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type CheckPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionResponse) Reset() {
	*x = CheckPermissionResponse{}
	mi := &file_proto_iam_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionResponse) ProtoMessage() {}

func (x *CheckPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionResponse.ProtoReflect.Descriptor instead.
func (*CheckPermissionResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_proto_rawDescGZIP(), []int{15}
}

func (x *CheckPermissionResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

var File_proto_iam_proto protoreflect.FileDescriptor

const file_proto_iam_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/iam.proto\x12\x06iam.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"`\n" +
	"\x11CreateUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"$\n" +
	"\x0eGetUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xd9\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"t\n" +
	"\x13CreatePolicyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12'\n" +
	"\x0fpolicy_document\x18\x03 \x01(\tR\x0epolicyDocument\"W\n" +
	"\x17AttachUserPolicyRequest\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x1f\n" +
	"\vpolicy_name\x18\x02 \x01(\tR\n" +
	"policyName\"4\n" +
	"\x18AttachUserPolicyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xed\x01\n" +
	"\x06Policy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12'\n" +
	"\x0fpolicy_document\x18\x04 \x01(\tR\x0epolicyDocument\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"5\n" +
	"\x16CreateAccessKeyRequest\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\"4\n" +
	"\x15ListAccessKeysRequest\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\"Z\n" +
	"\x1cUpdateAccessKeyStatusRequest\x12\"\n" +
	"\raccess_key_id\x18\x01 \x01(\tR\vaccessKeyId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x86\x02\n" +
	"\tAccessKey\x12\"\n" +
	"\raccess_key_id\x18\x01 \x01(\tR\vaccessKeyId\x12*\n" +
	"\x11secret_access_key\x18\x02 \x01(\tR\x0fsecretAccessKey\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\tuser_name\x18\x04 \x01(\tR\buserName\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"L\n" +
	"\x16ListAccessKeysResponse\x122\n" +
	"\vaccess_keys\x18\x01 \x03(\v2\x11.iam.v1.AccessKeyR\n" +
	"accessKeys\"\x92\x01\n" +
	"\rVerifyRequest\x12\"\n" +
	"\raccess_key_id\x18\x01 \x01(\tR\vaccessKeyId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12!\n" +
	"\frequest_data\x18\x03 \x01(\tR\vrequestData\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"C\n" +
	"\x0eVerifyResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\"i\n" +
	"\x16CheckPermissionRequest\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\"3\n" +
	"\x17CheckPermissionResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed2\x92\x05\n" +
	"\x03IAM\x127\n" +
	"\n" +
	"CreateUser\x12\x19.iam.v1.CreateUserRequest\x1a\f.iam.v1.User\"\x00\x121\n" +
	"\aGetUser\x12\x16.iam.v1.GetUserRequest\x1a\f.iam.v1.User\"\x00\x12=\n" +
	"\fCreatePolicy\x12\x1b.iam.v1.CreatePolicyRequest\x1a\x0e.iam.v1.Policy\"\x00\x12W\n" +
	"\x10AttachUserPolicy\x12\x1f.iam.v1.AttachUserPolicyRequest\x1a .iam.v1.AttachUserPolicyResponse\"\x00\x12F\n" +
	"\x0fCreateAccessKey\x12\x1e.iam.v1.CreateAccessKeyRequest\x1a\x11.iam.v1.AccessKey\"\x00\x12Q\n" +
	"\x0eListAccessKeys\x12\x1d.iam.v1.ListAccessKeysRequest\x1a\x1e.iam.v1.ListAccessKeysResponse\"\x00\x12R\n" +
	"\x15UpdateAccessKeyStatus\x12$.iam.v1.UpdateAccessKeyStatusRequest\x1a\x11.iam.v1.AccessKey\"\x00\x12B\n" +
	"\x0fVerifyAccessKey\x12\x15.iam.v1.VerifyRequest\x1a\x16.iam.v1.VerifyResponse\"\x00\x12T\n" +
	"\x0fCheckPermission\x12\x1e.iam.v1.CheckPermissionRequest\x1a\x1f.iam.v1.CheckPermissionResponse\"\x00B3Z1github.com/vera-byte/vgo-iam/internal/proto;iamv1b\x06proto3"

var (
	file_proto_iam_proto_rawDescOnce sync.Once
	file_proto_iam_proto_rawDescData []byte
)

func file_proto_iam_proto_rawDescGZIP() []byte {
	file_proto_iam_proto_rawDescOnce.Do(func() {
		file_proto_iam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_iam_proto_rawDesc), len(file_proto_iam_proto_rawDesc)))
	})
	return file_proto_iam_proto_rawDescData
}

var file_proto_iam_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_iam_proto_goTypes = []any{
	(*CreateUserRequest)(nil),            // 0: iam.v1.CreateUserRequest
	(*GetUserRequest)(nil),               // 1: iam.v1.GetUserRequest
	(*User)(nil),                         // 2: iam.v1.User
	(*CreatePolicyRequest)(nil),          // 3: iam.v1.CreatePolicyRequest
	(*AttachUserPolicyRequest)(nil),      // 4: iam.v1.AttachUserPolicyRequest
	(*AttachUserPolicyResponse)(nil),     // 5: iam.v1.AttachUserPolicyResponse
	(*Policy)(nil),                       // 6: iam.v1.Policy
	(*CreateAccessKeyRequest)(nil),       // 7: iam.v1.CreateAccessKeyRequest
	(*ListAccessKeysRequest)(nil),        // 8: iam.v1.ListAccessKeysRequest
	(*UpdateAccessKeyStatusRequest)(nil), // 9: iam.v1.UpdateAccessKeyStatusRequest
	(*AccessKey)(nil),                    // 10: iam.v1.AccessKey
	(*ListAccessKeysResponse)(nil),       // 11: iam.v1.ListAccessKeysResponse
	(*VerifyRequest)(nil),                // 12: iam.v1.VerifyRequest
	(*VerifyResponse)(nil),               // 13: iam.v1.VerifyResponse
	(*CheckPermissionRequest)(nil),       // 14: iam.v1.CheckPermissionRequest
	(*CheckPermissionResponse)(nil),      // 15: iam.v1.CheckPermissionResponse
	(*timestamppb.Timestamp)(nil),        // 16: google.protobuf.Timestamp
}
var file_proto_iam_proto_depIdxs = []int32{
	16, // 0: iam.v1.User.created_at:type_name -> google.protobuf.Timestamp
	16, // 1: iam.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	16, // 2: iam.v1.Policy.created_at:type_name -> google.protobuf.Timestamp
	16, // 3: iam.v1.Policy.updated_at:type_name -> google.protobuf.Timestamp
	16, // 4: iam.v1.AccessKey.created_at:type_name -> google.protobuf.Timestamp
	16, // 5: iam.v1.AccessKey.updated_at:type_name -> google.protobuf.Timestamp
	10, // 6: iam.v1.ListAccessKeysResponse.access_keys:type_name -> iam.v1.AccessKey
	0,  // 7: iam.v1.IAM.CreateUser:input_type -> iam.v1.CreateUserRequest
	1,  // 8: iam.v1.IAM.GetUser:input_type -> iam.v1.GetUserRequest
	3,  // 9: iam.v1.IAM.CreatePolicy:input_type -> iam.v1.CreatePolicyRequest
	4,  // 10: iam.v1.IAM.AttachUserPolicy:input_type -> iam.v1.AttachUserPolicyRequest
	7,  // 11: iam.v1.IAM.CreateAccessKey:input_type -> iam.v1.CreateAccessKeyRequest
	8,  // 12: iam.v1.IAM.ListAccessKeys:input_type -> iam.v1.ListAccessKeysRequest
	9,  // 13: iam.v1.IAM.UpdateAccessKeyStatus:input_type -> iam.v1.UpdateAccessKeyStatusRequest
	12, // 14: iam.v1.IAM.VerifyAccessKey:input_type -> iam.v1.VerifyRequest
	14, // 15: iam.v1.IAM.CheckPermission:input_type -> iam.v1.CheckPermissionRequest
	2,  // 16: iam.v1.IAM.CreateUser:output_type -> iam.v1.User
	2,  // 17: iam.v1.IAM.GetUser:output_type -> iam.v1.User
	6,  // 18: iam.v1.IAM.CreatePolicy:output_type -> iam.v1.Policy
	5,  // 19: iam.v1.IAM.AttachUserPolicy:output_type -> iam.v1.AttachUserPolicyResponse
	10, // 20: iam.v1.IAM.CreateAccessKey:output_type -> iam.v1.AccessKey
	11, // 21: iam.v1.IAM.ListAccessKeys:output_type -> iam.v1.ListAccessKeysResponse
	10, // 22: iam.v1.IAM.UpdateAccessKeyStatus:output_type -> iam.v1.AccessKey
	13, // 23: iam.v1.IAM.VerifyAccessKey:output_type -> iam.v1.VerifyResponse
	15, // 24: iam.v1.IAM.CheckPermission:output_type -> iam.v1.CheckPermissionResponse
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_iam_proto_init() }
func file_proto_iam_proto_init() {
	if File_proto_iam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_iam_proto_rawDesc), len(file_proto_iam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_iam_proto_goTypes,
		DependencyIndexes: file_proto_iam_proto_depIdxs,
		MessageInfos:      file_proto_iam_proto_msgTypes,
	}.Build()
	File_proto_iam_proto = out.File
	file_proto_iam_proto_goTypes = nil
	file_proto_iam_proto_depIdxs = nil
}
