// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: proto/iam.proto

package iamv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IAM_CreateUser_FullMethodName                  = "/iam.v1.IAM/CreateUser"
	IAM_GetUser_FullMethodName                     = "/iam.v1.IAM/GetUser"
	IAM_ListUsers_FullMethodName                   = "/iam.v1.IAM/ListUsers"
	IAM_UpdateUser_FullMethodName                  = "/iam.v1.IAM/UpdateUser"
	IAM_DeleteUser_FullMethodName                  = "/iam.v1.IAM/DeleteUser"
	IAM_CreatePolicy_FullMethodName                = "/iam.v1.IAM/CreatePolicy"
	IAM_ListPolicies_FullMethodName                = "/iam.v1.IAM/ListPolicies"
	IAM_AttachUserPolicy_FullMethodName            = "/iam.v1.IAM/AttachUserPolicy"
	IAM_SubmitDeveloperVerification_FullMethodName = "/iam.v1.IAM/SubmitDeveloperVerification"
	IAM_GetDeveloperVerification_FullMethodName    = "/iam.v1.IAM/GetDeveloperVerification"
	IAM_ListDeveloperVerifications_FullMethodName  = "/iam.v1.IAM/ListDeveloperVerifications"
	IAM_ReviewDeveloperVerification_FullMethodName = "/iam.v1.IAM/ReviewDeveloperVerification"
	IAM_CreateApplication_FullMethodName           = "/iam.v1.IAM/CreateApplication"
	IAM_GetApplication_FullMethodName              = "/iam.v1.IAM/GetApplication"
	IAM_ListApplications_FullMethodName            = "/iam.v1.IAM/ListApplications"
	IAM_UpdateApplication_FullMethodName           = "/iam.v1.IAM/UpdateApplication"
	IAM_DeleteApplication_FullMethodName           = "/iam.v1.IAM/DeleteApplication"
	IAM_CreateAccessKey_FullMethodName             = "/iam.v1.IAM/CreateAccessKey"
	IAM_ListAccessKeys_FullMethodName              = "/iam.v1.IAM/ListAccessKeys"
	IAM_UpdateAccessKeyStatus_FullMethodName       = "/iam.v1.IAM/UpdateAccessKeyStatus"
	IAM_VerifyAccessKey_FullMethodName             = "/iam.v1.IAM/VerifyAccessKey"
	IAM_CheckPermission_FullMethodName             = "/iam.v1.IAM/CheckPermission"
	IAM_ValidatePermission_FullMethodName          = "/iam.v1.IAM/ValidatePermission"
	IAM_AssumeRole_FullMethodName                  = "/iam.v1.IAM/AssumeRole"
	IAM_GetSessionToken_FullMethodName             = "/iam.v1.IAM/GetSessionToken"
	IAM_RefreshToken_FullMethodName                = "/iam.v1.IAM/RefreshToken"
	IAM_RevokeToken_FullMethodName                 = "/iam.v1.IAM/RevokeToken"
	IAM_GetDashboardStats_FullMethodName           = "/iam.v1.IAM/GetDashboardStats"
	IAM_GetDashboardStatus_FullMethodName          = "/iam.v1.IAM/GetDashboardStatus"
	IAM_GetDashboardActivities_FullMethodName      = "/iam.v1.IAM/GetDashboardActivities"
)

// IAMClient is the client API for IAM service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IAMClient interface {
	// 创建用户
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error)
	// 获取用户
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	// 用户列表
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	// 更新用户
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error)
	// 删除用户
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	// 策略管理
	// 创建策略
	CreatePolicy(ctx context.Context, in *CreatePolicyRequest, opts ...grpc.CallOption) (*Policy, error)
	// 获取策略列表
	ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*ListPoliciesResponse, error)
	// 附加用户策略
	AttachUserPolicy(ctx context.Context, in *AttachUserPolicyRequest, opts ...grpc.CallOption) (*AttachUserPolicyResponse, error)
	// 开发者认证管理
	// 提交开发者认证
	SubmitDeveloperVerification(ctx context.Context, in *SubmitDeveloperVerificationRequest, opts ...grpc.CallOption) (*DeveloperVerification, error)
	// 获取开发者认证
	GetDeveloperVerification(ctx context.Context, in *GetDeveloperVerificationRequest, opts ...grpc.CallOption) (*DeveloperVerification, error)
	// 开发者认证列表
	ListDeveloperVerifications(ctx context.Context, in *ListDeveloperVerificationsRequest, opts ...grpc.CallOption) (*ListDeveloperVerificationsResponse, error)
	// 审核开发者认证
	ReviewDeveloperVerification(ctx context.Context, in *ReviewDeveloperVerificationRequest, opts ...grpc.CallOption) (*DeveloperVerification, error)
	// 应用管理
	// 创建应用
	CreateApplication(ctx context.Context, in *CreateApplicationRequest, opts ...grpc.CallOption) (*Application, error)
	// 获取应用
	GetApplication(ctx context.Context, in *GetApplicationRequest, opts ...grpc.CallOption) (*Application, error)
	// 应用列表
	ListApplications(ctx context.Context, in *ListApplicationsRequest, opts ...grpc.CallOption) (*ListApplicationsResponse, error)
	// 更新应用
	UpdateApplication(ctx context.Context, in *UpdateApplicationRequest, opts ...grpc.CallOption) (*Application, error)
	// 删除应用
	DeleteApplication(ctx context.Context, in *DeleteApplicationRequest, opts ...grpc.CallOption) (*DeleteApplicationResponse, error)
	// 访问密钥管理
	// 创建访问密钥
	CreateAccessKey(ctx context.Context, in *CreateAccessKeyRequest, opts ...grpc.CallOption) (*AccessKey, error)
	// 访问密钥列表
	ListAccessKeys(ctx context.Context, in *ListAccessKeysRequest, opts ...grpc.CallOption) (*ListAccessKeysResponse, error)
	// 更新访问密钥状态
	UpdateAccessKeyStatus(ctx context.Context, in *UpdateAccessKeyStatusRequest, opts ...grpc.CallOption) (*AccessKey, error)
	// 权限验证
	// 验证访问密钥
	VerifyAccessKey(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
	// 检查权限
	CheckPermission(ctx context.Context, in *CheckPermissionRequest, opts ...grpc.CallOption) (*CheckPermissionResponse, error)
	// 验证权限
	ValidatePermission(ctx context.Context, in *ValidatePermissionRequest, opts ...grpc.CallOption) (*ValidatePermissionResponse, error)
	// STS临时授权服务
	// 假设角色
	AssumeRole(ctx context.Context, in *AssumeRoleRequest, opts ...grpc.CallOption) (*AssumeRoleResponse, error)
	// 获取会话令牌
	GetSessionToken(ctx context.Context, in *GetSessionTokenRequest, opts ...grpc.CallOption) (*GetSessionTokenResponse, error)
	// 刷新令牌
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	// 撤销令牌
	RevokeToken(ctx context.Context, in *RevokeTokenRequest, opts ...grpc.CallOption) (*RevokeTokenResponse, error)
	// Dashboard相关接口
	// 获取统计数据
	GetDashboardStats(ctx context.Context, in *DashboardStatsRequest, opts ...grpc.CallOption) (*DashboardStatsResponse, error)
	// 获取系统状态
	GetDashboardStatus(ctx context.Context, in *DashboardStatusRequest, opts ...grpc.CallOption) (*DashboardStatusResponse, error)
	// 获取最近活动
	GetDashboardActivities(ctx context.Context, in *DashboardActivitiesRequest, opts ...grpc.CallOption) (*DashboardActivitiesResponse, error)
}

type iAMClient struct {
	cc grpc.ClientConnInterface
}

func NewIAMClient(cc grpc.ClientConnInterface) IAMClient {
	return &iAMClient{cc}
}

func (c *iAMClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, IAM_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, IAM_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, IAM_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, IAM_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, IAM_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) CreatePolicy(ctx context.Context, in *CreatePolicyRequest, opts ...grpc.CallOption) (*Policy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Policy)
	err := c.cc.Invoke(ctx, IAM_CreatePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*ListPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPoliciesResponse)
	err := c.cc.Invoke(ctx, IAM_ListPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) AttachUserPolicy(ctx context.Context, in *AttachUserPolicyRequest, opts ...grpc.CallOption) (*AttachUserPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachUserPolicyResponse)
	err := c.cc.Invoke(ctx, IAM_AttachUserPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) SubmitDeveloperVerification(ctx context.Context, in *SubmitDeveloperVerificationRequest, opts ...grpc.CallOption) (*DeveloperVerification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeveloperVerification)
	err := c.cc.Invoke(ctx, IAM_SubmitDeveloperVerification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) GetDeveloperVerification(ctx context.Context, in *GetDeveloperVerificationRequest, opts ...grpc.CallOption) (*DeveloperVerification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeveloperVerification)
	err := c.cc.Invoke(ctx, IAM_GetDeveloperVerification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) ListDeveloperVerifications(ctx context.Context, in *ListDeveloperVerificationsRequest, opts ...grpc.CallOption) (*ListDeveloperVerificationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeveloperVerificationsResponse)
	err := c.cc.Invoke(ctx, IAM_ListDeveloperVerifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) ReviewDeveloperVerification(ctx context.Context, in *ReviewDeveloperVerificationRequest, opts ...grpc.CallOption) (*DeveloperVerification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeveloperVerification)
	err := c.cc.Invoke(ctx, IAM_ReviewDeveloperVerification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) CreateApplication(ctx context.Context, in *CreateApplicationRequest, opts ...grpc.CallOption) (*Application, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Application)
	err := c.cc.Invoke(ctx, IAM_CreateApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) GetApplication(ctx context.Context, in *GetApplicationRequest, opts ...grpc.CallOption) (*Application, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Application)
	err := c.cc.Invoke(ctx, IAM_GetApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) ListApplications(ctx context.Context, in *ListApplicationsRequest, opts ...grpc.CallOption) (*ListApplicationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListApplicationsResponse)
	err := c.cc.Invoke(ctx, IAM_ListApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) UpdateApplication(ctx context.Context, in *UpdateApplicationRequest, opts ...grpc.CallOption) (*Application, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Application)
	err := c.cc.Invoke(ctx, IAM_UpdateApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) DeleteApplication(ctx context.Context, in *DeleteApplicationRequest, opts ...grpc.CallOption) (*DeleteApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteApplicationResponse)
	err := c.cc.Invoke(ctx, IAM_DeleteApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) CreateAccessKey(ctx context.Context, in *CreateAccessKeyRequest, opts ...grpc.CallOption) (*AccessKey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessKey)
	err := c.cc.Invoke(ctx, IAM_CreateAccessKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) ListAccessKeys(ctx context.Context, in *ListAccessKeysRequest, opts ...grpc.CallOption) (*ListAccessKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAccessKeysResponse)
	err := c.cc.Invoke(ctx, IAM_ListAccessKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) UpdateAccessKeyStatus(ctx context.Context, in *UpdateAccessKeyStatusRequest, opts ...grpc.CallOption) (*AccessKey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessKey)
	err := c.cc.Invoke(ctx, IAM_UpdateAccessKeyStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) VerifyAccessKey(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, IAM_VerifyAccessKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) CheckPermission(ctx context.Context, in *CheckPermissionRequest, opts ...grpc.CallOption) (*CheckPermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPermissionResponse)
	err := c.cc.Invoke(ctx, IAM_CheckPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) ValidatePermission(ctx context.Context, in *ValidatePermissionRequest, opts ...grpc.CallOption) (*ValidatePermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidatePermissionResponse)
	err := c.cc.Invoke(ctx, IAM_ValidatePermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) AssumeRole(ctx context.Context, in *AssumeRoleRequest, opts ...grpc.CallOption) (*AssumeRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssumeRoleResponse)
	err := c.cc.Invoke(ctx, IAM_AssumeRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) GetSessionToken(ctx context.Context, in *GetSessionTokenRequest, opts ...grpc.CallOption) (*GetSessionTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionTokenResponse)
	err := c.cc.Invoke(ctx, IAM_GetSessionToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, IAM_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) RevokeToken(ctx context.Context, in *RevokeTokenRequest, opts ...grpc.CallOption) (*RevokeTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeTokenResponse)
	err := c.cc.Invoke(ctx, IAM_RevokeToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) GetDashboardStats(ctx context.Context, in *DashboardStatsRequest, opts ...grpc.CallOption) (*DashboardStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DashboardStatsResponse)
	err := c.cc.Invoke(ctx, IAM_GetDashboardStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) GetDashboardStatus(ctx context.Context, in *DashboardStatusRequest, opts ...grpc.CallOption) (*DashboardStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DashboardStatusResponse)
	err := c.cc.Invoke(ctx, IAM_GetDashboardStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) GetDashboardActivities(ctx context.Context, in *DashboardActivitiesRequest, opts ...grpc.CallOption) (*DashboardActivitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DashboardActivitiesResponse)
	err := c.cc.Invoke(ctx, IAM_GetDashboardActivities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IAMServer is the server API for IAM service.
// All implementations should embed UnimplementedIAMServer
// for forward compatibility.
type IAMServer interface {
	// 创建用户
	CreateUser(context.Context, *CreateUserRequest) (*User, error)
	// 获取用户
	GetUser(context.Context, *GetUserRequest) (*User, error)
	// 用户列表
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	// 更新用户
	UpdateUser(context.Context, *UpdateUserRequest) (*User, error)
	// 删除用户
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	// 策略管理
	// 创建策略
	CreatePolicy(context.Context, *CreatePolicyRequest) (*Policy, error)
	// 获取策略列表
	ListPolicies(context.Context, *ListPoliciesRequest) (*ListPoliciesResponse, error)
	// 附加用户策略
	AttachUserPolicy(context.Context, *AttachUserPolicyRequest) (*AttachUserPolicyResponse, error)
	// 开发者认证管理
	// 提交开发者认证
	SubmitDeveloperVerification(context.Context, *SubmitDeveloperVerificationRequest) (*DeveloperVerification, error)
	// 获取开发者认证
	GetDeveloperVerification(context.Context, *GetDeveloperVerificationRequest) (*DeveloperVerification, error)
	// 开发者认证列表
	ListDeveloperVerifications(context.Context, *ListDeveloperVerificationsRequest) (*ListDeveloperVerificationsResponse, error)
	// 审核开发者认证
	ReviewDeveloperVerification(context.Context, *ReviewDeveloperVerificationRequest) (*DeveloperVerification, error)
	// 应用管理
	// 创建应用
	CreateApplication(context.Context, *CreateApplicationRequest) (*Application, error)
	// 获取应用
	GetApplication(context.Context, *GetApplicationRequest) (*Application, error)
	// 应用列表
	ListApplications(context.Context, *ListApplicationsRequest) (*ListApplicationsResponse, error)
	// 更新应用
	UpdateApplication(context.Context, *UpdateApplicationRequest) (*Application, error)
	// 删除应用
	DeleteApplication(context.Context, *DeleteApplicationRequest) (*DeleteApplicationResponse, error)
	// 访问密钥管理
	// 创建访问密钥
	CreateAccessKey(context.Context, *CreateAccessKeyRequest) (*AccessKey, error)
	// 访问密钥列表
	ListAccessKeys(context.Context, *ListAccessKeysRequest) (*ListAccessKeysResponse, error)
	// 更新访问密钥状态
	UpdateAccessKeyStatus(context.Context, *UpdateAccessKeyStatusRequest) (*AccessKey, error)
	// 权限验证
	// 验证访问密钥
	VerifyAccessKey(context.Context, *VerifyRequest) (*VerifyResponse, error)
	// 检查权限
	CheckPermission(context.Context, *CheckPermissionRequest) (*CheckPermissionResponse, error)
	// 验证权限
	ValidatePermission(context.Context, *ValidatePermissionRequest) (*ValidatePermissionResponse, error)
	// STS临时授权服务
	// 假设角色
	AssumeRole(context.Context, *AssumeRoleRequest) (*AssumeRoleResponse, error)
	// 获取会话令牌
	GetSessionToken(context.Context, *GetSessionTokenRequest) (*GetSessionTokenResponse, error)
	// 刷新令牌
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	// 撤销令牌
	RevokeToken(context.Context, *RevokeTokenRequest) (*RevokeTokenResponse, error)
	// Dashboard相关接口
	// 获取统计数据
	GetDashboardStats(context.Context, *DashboardStatsRequest) (*DashboardStatsResponse, error)
	// 获取系统状态
	GetDashboardStatus(context.Context, *DashboardStatusRequest) (*DashboardStatusResponse, error)
	// 获取最近活动
	GetDashboardActivities(context.Context, *DashboardActivitiesRequest) (*DashboardActivitiesResponse, error)
}

// UnimplementedIAMServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIAMServer struct{}

func (UnimplementedIAMServer) CreateUser(context.Context, *CreateUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedIAMServer) GetUser(context.Context, *GetUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedIAMServer) ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedIAMServer) UpdateUser(context.Context, *UpdateUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedIAMServer) DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedIAMServer) CreatePolicy(context.Context, *CreatePolicyRequest) (*Policy, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePolicy not implemented")
}
func (UnimplementedIAMServer) ListPolicies(context.Context, *ListPoliciesRequest) (*ListPoliciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPolicies not implemented")
}
func (UnimplementedIAMServer) AttachUserPolicy(context.Context, *AttachUserPolicyRequest) (*AttachUserPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttachUserPolicy not implemented")
}
func (UnimplementedIAMServer) SubmitDeveloperVerification(context.Context, *SubmitDeveloperVerificationRequest) (*DeveloperVerification, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitDeveloperVerification not implemented")
}
func (UnimplementedIAMServer) GetDeveloperVerification(context.Context, *GetDeveloperVerificationRequest) (*DeveloperVerification, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeveloperVerification not implemented")
}
func (UnimplementedIAMServer) ListDeveloperVerifications(context.Context, *ListDeveloperVerificationsRequest) (*ListDeveloperVerificationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeveloperVerifications not implemented")
}
func (UnimplementedIAMServer) ReviewDeveloperVerification(context.Context, *ReviewDeveloperVerificationRequest) (*DeveloperVerification, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReviewDeveloperVerification not implemented")
}
func (UnimplementedIAMServer) CreateApplication(context.Context, *CreateApplicationRequest) (*Application, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateApplication not implemented")
}
func (UnimplementedIAMServer) GetApplication(context.Context, *GetApplicationRequest) (*Application, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApplication not implemented")
}
func (UnimplementedIAMServer) ListApplications(context.Context, *ListApplicationsRequest) (*ListApplicationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListApplications not implemented")
}
func (UnimplementedIAMServer) UpdateApplication(context.Context, *UpdateApplicationRequest) (*Application, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateApplication not implemented")
}
func (UnimplementedIAMServer) DeleteApplication(context.Context, *DeleteApplicationRequest) (*DeleteApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteApplication not implemented")
}
func (UnimplementedIAMServer) CreateAccessKey(context.Context, *CreateAccessKeyRequest) (*AccessKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccessKey not implemented")
}
func (UnimplementedIAMServer) ListAccessKeys(context.Context, *ListAccessKeysRequest) (*ListAccessKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAccessKeys not implemented")
}
func (UnimplementedIAMServer) UpdateAccessKeyStatus(context.Context, *UpdateAccessKeyStatusRequest) (*AccessKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAccessKeyStatus not implemented")
}
func (UnimplementedIAMServer) VerifyAccessKey(context.Context, *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyAccessKey not implemented")
}
func (UnimplementedIAMServer) CheckPermission(context.Context, *CheckPermissionRequest) (*CheckPermissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPermission not implemented")
}
func (UnimplementedIAMServer) ValidatePermission(context.Context, *ValidatePermissionRequest) (*ValidatePermissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidatePermission not implemented")
}
func (UnimplementedIAMServer) AssumeRole(context.Context, *AssumeRoleRequest) (*AssumeRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssumeRole not implemented")
}
func (UnimplementedIAMServer) GetSessionToken(context.Context, *GetSessionTokenRequest) (*GetSessionTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionToken not implemented")
}
func (UnimplementedIAMServer) RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedIAMServer) RevokeToken(context.Context, *RevokeTokenRequest) (*RevokeTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeToken not implemented")
}
func (UnimplementedIAMServer) GetDashboardStats(context.Context, *DashboardStatsRequest) (*DashboardStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardStats not implemented")
}
func (UnimplementedIAMServer) GetDashboardStatus(context.Context, *DashboardStatusRequest) (*DashboardStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardStatus not implemented")
}
func (UnimplementedIAMServer) GetDashboardActivities(context.Context, *DashboardActivitiesRequest) (*DashboardActivitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardActivities not implemented")
}
func (UnimplementedIAMServer) testEmbeddedByValue() {}

// UnsafeIAMServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IAMServer will
// result in compilation errors.
type UnsafeIAMServer interface {
	mustEmbedUnimplementedIAMServer()
}

func RegisterIAMServer(s grpc.ServiceRegistrar, srv IAMServer) {
	// If the following call pancis, it indicates UnimplementedIAMServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IAM_ServiceDesc, srv)
}

func _IAM_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_CreatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).CreatePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_CreatePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).CreatePolicy(ctx, req.(*CreatePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_ListPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).ListPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_ListPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).ListPolicies(ctx, req.(*ListPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_AttachUserPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachUserPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).AttachUserPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_AttachUserPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).AttachUserPolicy(ctx, req.(*AttachUserPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_SubmitDeveloperVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitDeveloperVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).SubmitDeveloperVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_SubmitDeveloperVerification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).SubmitDeveloperVerification(ctx, req.(*SubmitDeveloperVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_GetDeveloperVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeveloperVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).GetDeveloperVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_GetDeveloperVerification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).GetDeveloperVerification(ctx, req.(*GetDeveloperVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_ListDeveloperVerifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeveloperVerificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).ListDeveloperVerifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_ListDeveloperVerifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).ListDeveloperVerifications(ctx, req.(*ListDeveloperVerificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_ReviewDeveloperVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewDeveloperVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).ReviewDeveloperVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_ReviewDeveloperVerification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).ReviewDeveloperVerification(ctx, req.(*ReviewDeveloperVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_CreateApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).CreateApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_CreateApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).CreateApplication(ctx, req.(*CreateApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_GetApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).GetApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_GetApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).GetApplication(ctx, req.(*GetApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_ListApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).ListApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_ListApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).ListApplications(ctx, req.(*ListApplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_UpdateApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).UpdateApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_UpdateApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).UpdateApplication(ctx, req.(*UpdateApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_DeleteApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).DeleteApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_DeleteApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).DeleteApplication(ctx, req.(*DeleteApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_CreateAccessKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccessKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).CreateAccessKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_CreateAccessKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).CreateAccessKey(ctx, req.(*CreateAccessKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_ListAccessKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccessKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).ListAccessKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_ListAccessKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).ListAccessKeys(ctx, req.(*ListAccessKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_UpdateAccessKeyStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccessKeyStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).UpdateAccessKeyStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_UpdateAccessKeyStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).UpdateAccessKeyStatus(ctx, req.(*UpdateAccessKeyStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_VerifyAccessKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).VerifyAccessKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_VerifyAccessKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).VerifyAccessKey(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_CheckPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).CheckPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_CheckPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).CheckPermission(ctx, req.(*CheckPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_ValidatePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidatePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).ValidatePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_ValidatePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).ValidatePermission(ctx, req.(*ValidatePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_AssumeRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssumeRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).AssumeRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_AssumeRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).AssumeRole(ctx, req.(*AssumeRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_GetSessionToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).GetSessionToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_GetSessionToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).GetSessionToken(ctx, req.(*GetSessionTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_RevokeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).RevokeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_RevokeToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).RevokeToken(ctx, req.(*RevokeTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_GetDashboardStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DashboardStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).GetDashboardStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_GetDashboardStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).GetDashboardStats(ctx, req.(*DashboardStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_GetDashboardStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DashboardStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).GetDashboardStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_GetDashboardStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).GetDashboardStatus(ctx, req.(*DashboardStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_GetDashboardActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DashboardActivitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).GetDashboardActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_GetDashboardActivities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).GetDashboardActivities(ctx, req.(*DashboardActivitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IAM_ServiceDesc is the grpc.ServiceDesc for IAM service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IAM_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iam.v1.IAM",
	HandlerType: (*IAMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _IAM_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _IAM_GetUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _IAM_ListUsers_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _IAM_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _IAM_DeleteUser_Handler,
		},
		{
			MethodName: "CreatePolicy",
			Handler:    _IAM_CreatePolicy_Handler,
		},
		{
			MethodName: "ListPolicies",
			Handler:    _IAM_ListPolicies_Handler,
		},
		{
			MethodName: "AttachUserPolicy",
			Handler:    _IAM_AttachUserPolicy_Handler,
		},
		{
			MethodName: "SubmitDeveloperVerification",
			Handler:    _IAM_SubmitDeveloperVerification_Handler,
		},
		{
			MethodName: "GetDeveloperVerification",
			Handler:    _IAM_GetDeveloperVerification_Handler,
		},
		{
			MethodName: "ListDeveloperVerifications",
			Handler:    _IAM_ListDeveloperVerifications_Handler,
		},
		{
			MethodName: "ReviewDeveloperVerification",
			Handler:    _IAM_ReviewDeveloperVerification_Handler,
		},
		{
			MethodName: "CreateApplication",
			Handler:    _IAM_CreateApplication_Handler,
		},
		{
			MethodName: "GetApplication",
			Handler:    _IAM_GetApplication_Handler,
		},
		{
			MethodName: "ListApplications",
			Handler:    _IAM_ListApplications_Handler,
		},
		{
			MethodName: "UpdateApplication",
			Handler:    _IAM_UpdateApplication_Handler,
		},
		{
			MethodName: "DeleteApplication",
			Handler:    _IAM_DeleteApplication_Handler,
		},
		{
			MethodName: "CreateAccessKey",
			Handler:    _IAM_CreateAccessKey_Handler,
		},
		{
			MethodName: "ListAccessKeys",
			Handler:    _IAM_ListAccessKeys_Handler,
		},
		{
			MethodName: "UpdateAccessKeyStatus",
			Handler:    _IAM_UpdateAccessKeyStatus_Handler,
		},
		{
			MethodName: "VerifyAccessKey",
			Handler:    _IAM_VerifyAccessKey_Handler,
		},
		{
			MethodName: "CheckPermission",
			Handler:    _IAM_CheckPermission_Handler,
		},
		{
			MethodName: "ValidatePermission",
			Handler:    _IAM_ValidatePermission_Handler,
		},
		{
			MethodName: "AssumeRole",
			Handler:    _IAM_AssumeRole_Handler,
		},
		{
			MethodName: "GetSessionToken",
			Handler:    _IAM_GetSessionToken_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _IAM_RefreshToken_Handler,
		},
		{
			MethodName: "RevokeToken",
			Handler:    _IAM_RevokeToken_Handler,
		},
		{
			MethodName: "GetDashboardStats",
			Handler:    _IAM_GetDashboardStats_Handler,
		},
		{
			MethodName: "GetDashboardStatus",
			Handler:    _IAM_GetDashboardStatus_Handler,
		},
		{
			MethodName: "GetDashboardActivities",
			Handler:    _IAM_GetDashboardActivities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/iam.proto",
}
